### PR TITLE
Use a single UpdateManager

### LINKED ISSUE #44: Update page doesn't show newest release version and notes
From:  atom/atom#12311

### Description

The atom updater, when there's a new update, always shows the currently-installed vesion.

### Steps to Reproduce

1. Launch atom
1. **DO NOT** open the about page
1. Wait until there's a new release
1. Click the Squirrel icon in the lower-right

**Expected behavior:**

The Restart & Update section on the About tab should show the newest release version and link to its notes.

**Actual behavior:**

The Restart & Update section shows the **currently-installed** version number and links to the **currently-installed** version's release notes.

image

### Versions

Windows version
```
ver
Microsoft Windows [Version 10.0.10586]
```

Atom version
```
atom --version
Atom: 1.9.2
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
```

Atom package manager version
```
apm --version
apm: 1.10.0
npm: 2.13.3
node: 0.10.40
python
git
Visual Studio
```

Since I'm on Windows, the `apm --version` colors may not be displaying correctly. I had a hard time reading the Node version output for that command.

Also, as far as I know, this has been happening at least since Atom 1.5 or 1.6. I just didn't think to report it until now.

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This is my second attempt to fix #44.  The main problem was that there were two UpdateManager instances in the codebase: one in `main.js`, and the second in `about.js` that was subsequently passed to the necessary Etch components.  When the UpdateManager instance in Main detected an update, it would create the Squirrel tooltip, which when clicked, would instantiate About.  About would then create its _own_ UpdateManager, which would have no clue that an update had been downloaded.  This eventually leads to #44 (since the states are independent of each instance, but the version info isn't).

The fix is to pass the UpdateManager created in Main to About, thus getting rid of the second UpdateManager.

### Alternate Designs

UpdateManager could potentially be refactored so that it must be single-instance (can't remember the exact term for this right now...but basically like `Math`).

### Benefits

See above.

### Possible Drawbacks

I had to do some odd updateManager disposal code when About is deactivated, or else one spec would hard crash, two would timeout, and one would fail.  Did some investigation and it looks like the listeners weren't being set up properly when it got reactivated.  I am unsure if there would be any drawbacks from that disposal code, or if it can be improved.

### Applicable Issues

Fixes #44

@petewalker care to do some more static code analysis? :grin:
A spec is included this time which fails on `master`, but passes on this branch.
Whitespace-insensitive diff (for the specs) is available at https://github.com/atom/about/compare/wl-single-update-manager?w=1.

/cc @damieng (primary package contact) - you may notice that this change is similar to the one I recently did in settings-view.  It's essentially the same fix and rationale behind that one.

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -13,26 +15,38 @@ export default {
...
+        this.showStatusBarIfNeeded()
+      }
     }))
   },
 
   deactivate () {
     this.model.destroy()
     if (this.statusBarTile) this.statusBarTile.destroy()
+
+    if (updateManager) {
```
Comment (50Wliu) [inline lib/main.js]: This is what I'm most worried about.

File: lib/main.js [hunk 2]
```diff
@@ -42,10 +56,14 @@ export default {
...
+      UpdateManager = UpdateManager || require('./update-manager')
+      updateManager = updateManager || new UpdateManager()
+
       About = About || require('./about')
       this.model = new About({
         uri: AboutURI,
-        currentVersion: atom.getVersion()
+        currentVersion: atom.getVersion(),
+        updateManager: updateManager
       })
```
Comment (petewalker) [inline lib/main.js]: Can this not be refactored out? It's very much like line 18 and onwards above?

File: lib/main.js (hunk 1 above)
Comment (petewalker) [inline lib/main.js]: What worries you - the truthyness or the disposal? This is getting to the outer bounds of my knowledge of atom internals...

Comment (50Wliu) [inline lib/main.js]: The disposal.  Don't worry if you're unable to give advice about this.
