### PR TITLE
Always listen to onDidCompleteDownloadingUpdate

### LINKED ISSUE #44: Update page doesn't show newest release version and notes
From:  atom/atom#12311

### Description

The atom updater, when there's a new update, always shows the currently-installed vesion.

### Steps to Reproduce

1. Launch atom
1. **DO NOT** open the about page
1. Wait until there's a new release
1. Click the Squirrel icon in the lower-right

**Expected behavior:**

The Restart & Update section on the About tab should show the newest release version and link to its notes.

**Actual behavior:**

The Restart & Update section shows the **currently-installed** version number and links to the **currently-installed** version's release notes.

image

### Versions

Windows version
```
ver
Microsoft Windows [Version 10.0.10586]
```

Atom version
```
atom --version
Atom: 1.9.2
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
```

Atom package manager version
```
apm --version
apm: 1.10.0
npm: 2.13.3
node: 0.10.40
python
git
Visual Studio
```

Since I'm on Windows, the `apm --version` colors may not be displaying correctly. I had a hard time reading the Node version output for that command.

Also, as far as I know, this has been happening at least since Atom 1.5 or 1.6. I just didn't think to report it until now.

### PR DESCRIPTION
**Pull request by 50Wliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

@petewalker noted in #44 that different parts of About listen to different update events.  `atom.onUpdateAvailable` seems to fire when an update starts downloading, and is what is currently used in `main.js`.  `atom.autoUpdater.onDidCompleteDownloadingUpdate` is fired when an update finishes downloading, and is what is currently used in `update-manager.js`.
Since the tooltip infers that the update has already been downloaded and is waiting to install, I replaced `onUpdateAvailable` with `onDidcompleteDownloadingUpdate` (and also because there's a todo in the Atom codebase about moving away from `onUpdateAvailable`).
In addition, I removed a check to make sure Atom is running a released version before checking for the download completion, because theoretically if Atom isn't running on a released version then it will never receive a download completion event.  This allowed some cleanup of the specs.

### Alternate Designs

I could have went with onUpdateAvailable instead of the other way around, but see above for why I didn't.

### Benefits

Some minor code deduplication.

### Possible Drawbacks

None that I can foresee.

### Applicable Issues
None

/cc @mnquintana

### CODE REVIEW

File: lib/update-manager.js [hunk 1]
```diff
@@ -29,8 +29,7 @@ export default class UpdateManager {
       atom.autoUpdater.onDidBeginDownloadingUpdate(() => {
         this.setState(DownloadingUpdate)
       }),
-      atom.autoUpdater.onDidCompleteDownloadingUpdate((detail) => {
-        let {releaseVersion} = detail
+      atom.autoUpdater.onDidCompleteDownloadingUpdate(({releaseVersion}) => {
```
Comment (petewalker) [inline lib/update-manager.js]: I'm not sure this fixes #44. The reason the correct version is not displaying is because it's being initialised as the current version on line 17. This subscription only fires if the about window has already been opened.
So, in the following workflow:

* Open fresh atom instance (do not open about page)
* `onDidCompleteDownloadingUpdate` event fires
* Event is picked up by `main.js`, squirrel icon appears
* Click squirrel to open about page
* `availableVersion` is set to `atom.getVersion()` (as at line 17)

**Comment by 50Wliu** [comment]
Yeah, I realized shortly after I submitted this that it didn't actually fix anything because of the delayed subscription.

**Comment by 50Wliu** [comment]
I'm merging this as code maintenance, not because it fixes any issues.  Will continue investigating later.
